name: CI Workflow - Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ppic-python:latest .

      - name: Run Docker container
        run: |
          docker run --rm \
          -e GITHUB_USER="${{ github.actor }}" \
          ppic-python:latest